### ISSUE TITLE
Alternative to faling if device is not available 

### ISSUE THREAD

**Issue by Sxx125** [zakuArbor/proxyAuth#17]
-currently opens connection if in paired list
-would fail to make a connection if out of range

how to improve
-try to connect until successful
-or cross-reference with the list of available devices(might be more time consuming)

**Comment by zakuArbor** [comment]
Can you give more details about this issue. I forgot this issue existed but it does seem somewhat similar to #19 except you are focusing on unable to connect to device because of range.
