### ISSUE TITLE
As a group, investigate whether we should integrate Ubertooth One  or not

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#2]
Furkan has suggested a hardware idea to use Ubertooth One for our project. 

**Deadline:** Tuesday 11:59pm
**Goal:** 
* Read up on bluetooth and investigate what we could do with Ubertooth
* Find a use case for Ubertooth
* Make a decision whether or not to order the device

**Device:** https://www.amazon.ca/Ubertooth-One-Aluminum-Enclosure-Bundle/dp/B07GBDD53W/

Each member who is interested should write their findings and ideas to this issue. Please stick to one post for all your findings and ideas and edit the post you wrote to add any additional findings you have found. You are free to create more posts if it's to ask questions or comment on someone's findings.

**Comment by zakuArbor** [comment]
Justification 1: For development on Linux PAM, we will need a bluetooth adapter since the VM needs bluetooth connection to work.

**Comment by kay911kay** [comment]
Justification 2: Ubertooth One has a built in monitoring mode, I can see potential to use this device as bluetooth signal repeater(monitor traffic and re-broadcast) to perform a proximity attack.

**Comment by kay911kay** [comment]
Currently awaiting approval on Ubertooth One in order to progress with other issues.

**Comment by zakuArbor** [comment]
I am going to close this issue since we have already acquired the Ubertooth One and I don't think anyone is interested in researching and writing up use cases for Ubertooth One other than what was discussed among the team and with Furkan.
