### ISSUE TITLE
Android: Close socket with server when connection is severed

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#21]
When the server closes the socket or terminates, the application should know that the program has been terminated and go back to the main page or at least have some indicator (i.e. toast) that the connection has been severed.

**Comment by zakuArbor** [comment]
@ArslanAhmedQ can you reference the commit that made this change. I would like to see a new activity be launched (switch page) or see a toast that will tell me that a socket has been closed. I have not seen any indication of that when I pulled master unless it's in a branch.

**Comment by ArslanAhmedQ** [comment]
I left it for testing required, I never closed it.

**Comment by ArslanAhmedQ** [comment]
It requires testing. It's still in progress

**Comment by zakuArbor** [comment]
Perhaps there is a misunderstanding what this issue is. I have created a new branch off from `androidAnu` and have worked on the two issues that are similar #19 and this issue since it's taking too long to finish.
