### ISSUE TITLE
Bluetooth Disconnected - Ubuntu 19.04 

### ISSUE THREAD

**Issue by kay911kay** [zakuArbor/proxyAuth#9]
I am experiencing an issue where pairing with a mobile device succeeds, however the device is immediately disconnected. Additionally, odd hiccups where pairing does not prompt passcode.  

Any fix or help will be appreciated.

**Comment by zakuArbor** [comment]
Is this issue still needed? Can we close the issue or place it on Hold?

**Comment by zakuArbor** [comment]
I have not heard a reply about this issue for over two weeks, I'll be closing this issue.
